<?php
// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//Menu constants

const ASYNCAPI_MODULE_NAME = "apigee_drupal8_asyncapi";
const ASYNCAPI_MODULE_SETTINGS_VAR = ASYNCAPI_MODULE_NAME . ".settings";
const ASYNCAPI_MODULE_CONFIG_ROOT = "config";

//AsyncAPI constants
const ASYNCAPI_PATH_VAR = 'page_path';
const ASYNCAPI_SPEC_FILE_VAR = 'spec-file';
const ASYNCAPI_SPEC_FILE_NAME_VAR = 'spec-file-name';
const ASYNCAPI_SPEC_FILE_ID_VAR = 'spec-file-id';
const ASYNCAPI_ACCESS_VAR = 'page_access';
const ASYNCAPI_MENU_ID_VAR = 'main_menu_id';
const ASYNCAPI_MENU_LINK_TITLE_VAR = 'menu_title';
const ASYNCAPI_MENU_LINK_ENABLED_VAR = 'menu_enabled';


const ASYNCAPI_ACCESS_EVERYONE = 'everyone';
const ASYNCAPI_ACCESS_LOGGED_IN = 'logged_in';
const ASYNCAPI_PATH_DEFAULT = 'async';